version: '3.8'

services:
  rpc-server:
    build:
      context: .
      dockerfile: rpc-server.Dockerfile
    image: llama-cpp-rpc-server
    ports:
      - "${PORT}:${PORT}"  # Expose the RPC port using env variable
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 