version: '3.8'

services:
  rpc-server:
    build:
      context: .
      dockerfile: rpc-server.Dockerfile
    image: llama-cpp-rpc-server
    ports:
      - "50052:50052"  # Expose the RPC port.  Important for external access.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 