version: '3.8'

services:
  llama-rpc-server:
    build:
      context: .
      dockerfile: rpc-server.Dockerfile
    image: llama-cpp-rpc-server
    ports:
      - "50052:50052"
    environment:
      - HOST=0.0.0.0
      - PORT=50052
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 